version: 0.2
 
phases:
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean
      - mvn install
    finally:
      - echo Exiting the build phase...
artifacts:
  files:
    - 'Dockerfile'
    - 'target/AdivaSpringMVCSimpleApp-0.0.1-SNAPSHOT.war'
    - 'DockerImageBuild/buildspec.yml'
    discard-paths: yes