version: 0.2
 
phases:
pre_build:
    commands:
      - echo Entered the pre build phase...
build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn clean
      - mvn install
    finally:
      - echo Exiting the build phase...
post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'Dockerfile'
    - 'target/AdivaSpringMVCSimpleApp-0.0.1-SNAPSHOT.war'
  discard-paths: yes